# Generated by Django 5.2.7 on 2025-10-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_task_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'التصنيف', 'verbose_name_plural': 'التصنيف'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'قائمة المشاريع', 'verbose_name_plural': 'قائمة المشاريع'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'المهام', 'verbose_name_plural': 'المهام'},
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'وضع التنفذ'), (2, 'مكتمل'), (3, 'معلق'), (4, 'ملغي')], default=1),
        ),
    ]
